### ISSUE TITLE
Update documentations with regexp/pipeline syntax

### ISSUE THREAD

**Issue by mattiasbpersson** [Affirm/jenkins-plugins#2]
It would be nice to have an example of how to specify a regular-expression with the plugin. Also how to specify it within a pipeline, but maybe pipeline is not supported at all?

**Comment by jimjh** [comment]
Hey Mattias,

- Pipeline is not supported (yet).
- regex example: `^(release|rc)-(v[0-9\.]+|[a-z0-9]+)$`

See https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
